/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.*;
import dao.*;
import connect.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhieu
 */
public class QLNhanVien extends javax.swing.JFrame {
    private NhanVienDao nvDao = new NhanVienDao();
    private NhanVien nvEdit;
    private ChiNhanhDao chiNhanhDao = new ChiNhanhDao();
    DefaultTableModel tableModel;
    public QLNhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        initCbChiNhanh();
        tableModel = (DefaultTableModel) tableNv.getModel();
        loadTable(nvDao.findAll());
    }
    private void initCbChiNhanh() {
        List<ChiNhanh> list = chiNhanhDao.findAll();
        for (ChiNhanh k : list) {
            cbSearchCn.addItem(k.getMaCN());
        }
    
    }
    public void loadTable(List<NhanVien> list) {
        tableModel.setRowCount(0 );
        for (NhanVien nv : list) {
            tableModel.addRow(new Object[]{
                nv.getMaNV(),
                nv.getHo(),
                nv.getTen(),
                nv.getDiachi(),
                nv.getNgaysinh(),
                nv.getLuong(),
                nv.getGhichu(),
                nv.getChinhanh().getMaCN()
            });
        }
    }
    private String getCbNChiNhanh() {
        if ("Chi Nhánh".equals(cbSearchCn.getSelectedItem().toString())) {
            return null;
        }
        return cbSearchCn.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNv = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNv = new javax.swing.JTextField();
        cbSearchCn = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnAddNv = new javax.swing.JButton();
        btnUpdateNv = new javax.swing.JButton();
        btnEditNv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableNv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ", "Tên", "Địa chỉ", "Ngày sinh", "Lương", "Ghi chú", "Chi nhánh"
            }
        ));
        jScrollPane1.setViewportView(tableNv);

        jLabel1.setText("Mã nhân viên");

        jLabel2.setText("Tên nhân viên");

        cbSearchCn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chi Nhánh" }));
        cbSearchCn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchCnActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAddNv.setText("Thêm nhân viên");
        btnAddNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNvActionPerformed(evt);
            }
        });

        btnUpdateNv.setText("Sửa nhân viên");
        btnUpdateNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNvActionPerformed(evt);
            }
        });

        btnEditNv.setText("Xóa nhân viên");
        btnEditNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaNv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSearchCn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenNv, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateNv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditNv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnAddNv))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateNv)
                            .addComponent(btnEditNv))))
                .addGap(14, 14, 14)
                .addComponent(cbSearchCn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ChiNhanh chiNhanhSelect = new ChiNhanh();
        chiNhanhSelect.setMaCN(getCbNChiNhanh());
        List<NhanVien> list = nvDao.search(
                new NhanVien(
                        Integer.parseInt(txtMaNv.getText()),
                        null,
                        txtTenNv.getText(),
                        null,
                        null, 
                        (float) 0.0,
                        null,
                        chiNhanhSelect
                        

                )
        );
        
        loadTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbSearchCnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchCnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSearchCnActionPerformed

    private void btnEditNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNvActionPerformed
        // TODO add your handling code here:
        try {
            String id = tableModel.getValueAt(tableNv.getSelectedRow(), 0).toString();
            int ok = JOptionPane.showConfirmDialog(rootPane, "Xóa nhân viên ?");
            if (ok == JOptionPane.YES_OPTION) {
                boolean r = nvDao.delete(id);
                if (!r) {
                    JOptionPane.showMessageDialog(rootPane, "Thất bại !");
                } else {
                    loadTable(nvDao.findAll());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn nhân viên ?");
        }
    }//GEN-LAST:event_btnEditNvActionPerformed

    private void btnAddNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNvActionPerformed
        // TODO add your handling code here:
        ThemNv themNv = new ThemNv(this, rootPaneCheckingEnabled);
        themNv.setVisible(true);
        themNv.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddNvActionPerformed

    private void btnUpdateNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNvActionPerformed
        // TODO add your handling code here:
        try {
            String id = tableModel.getValueAt(tableNv.getSelectedRow(), 0).toString();
            nvEdit = nvDao.findByMaNv(id);
            SuaNv suaNv = new SuaNv(this, rootPaneCheckingEnabled);
            suaNv.setVisible(true);
            suaNv.setLocationRelativeTo(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn nhân viên ?");
        }
    }//GEN-LAST:event_btnUpdateNvActionPerformed

    public NhanVien getNvEdit() {
        return nvEdit;
    }

    public void setNvEdit(NhanVien nvEdit) {
        this.nvEdit = nvEdit;
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNv;
    private javax.swing.JButton btnEditNv;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateNv;
    private javax.swing.JComboBox<String> cbSearchCn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNv;
    private javax.swing.JTextField txtMaNv;
    private javax.swing.JTextField txtTenNv;
    // End of variables declaration//GEN-END:variables
}
